dist: trusty

install:
  - sudo apt-get install cowsay
  - export PATH=/usr/bin:/bin:/usr/games

script: 
  - cowsay "Howdy"
  - cowsay "Howdy" | cowsay -n
  - cowsay "Howdy" | cowsay -n | cowsay -n
  - cowsay "Howdy" | cowsay -n | cowsay -n | cowsay -n
  - cowsay "Howdy" | cowsay -n | cowsay -n | cowsay -n | cowsay -n
  - cowsay "Howdy" | cowsay -n | cowsay -n | cowsay -n | cowsay -n | cowsay -n
  - cowsay "Howdy" | cowsay -n -f stegosaurus

